pg_main:
  addr: "localhost:15432"
  user: "postgres"
  password: "postgres"
  database: "postgres"

sources_listener:
  addr: "localhost:29091"
  topic: "platform.sources.event-stream"
  group_id: "hccm-sources"
